version: '3.8'

services:
  postgre:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - ./configs:/docker-entrypoint-initdb.d
